### ISSUE TITLE
能否将运行所需的数据上传

### ISSUE THREAD

**Issue by WLYwangluyao** [cytan17726/KBQA-QueryGraphSelection#1]
您好，我想学习一下您的CKBQA，能否将readme稍微丰富一下，以及将相应的数据上传。代码中有很多9750_trainset_withAnswerType_seq 这样的文件，是怎样生成的呢。 # # #

**Comment by cytan17726** [comment]
感谢您的关注！

这个项目并不是我们工作最终的开源地址，后续正式版本会发布在https://github.com/EnernityTwinkle/KBQA-QueryGraphSelection
代码数据还在整理中，后续会调整部分代码、上传数据并进一步丰富readme，我尽量在国庆假期结束前搞定

seq文件是由查询图转候选化为的序列，您可以视为排序模型的输入

我们主要关注的是查询图排序部分，如果您希望获得的是一个完整的CKBQA系统，可以考虑别的仓库

再次感谢您的关注与issue！
